### ISSUE TITLE
No tracking preference

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#2490]
Here "tracking" means "sharing information with third parties for the purposes of software stability monitoring and analytics," and specifically in our case means "explicitly and deliberately sharing such information with Google and New Relic."

I am assuming that people who don't want to share crash information (e.g. what your app was doing when it crashed) also don't want to share general behavioral information (e.g. the number of times you check the dashboard every day).

I am also assuming people have the same preference on the website as in the mobile apps.

TODO
- [x] Add a `prefers_no_tracking` user preference
- [x] Text for this preference should read "Do not collect stability and usage data using third party services"
- [x] Add the following explanator text available in an "About" popup:

> We use a variety of third party services to monitor stability and diagnose bugs and problems in our software. These third parties include
>
> • Google (Google Analytics, Firebase Crashlytics)
> • New Relic
>
> Information we share with these third parties include
>
> • IP addresses (which can be used to derive location at city-level resolution, and to track you > • across different websites and services)
> • Browser details, like make, model, and version
> • Crash details, like exactly what line of code caused a crash
> • Device details, like make and model of a mobile phone
>
> These third party services provide enormous value to us in maintaining the stability and usability of iNaturalist with our relatively small staff. On mobile devices, there is almost no other way we can gain insight into problems that are occurring, since the software is running on devices we do not control. Sometimes we aren’t even aware such problems are occurring until we see them in the data these services provide. By sharing this information, you are helping us serve you and the entire iNaturalist community.
>
> Note that this option only applies to analytics and crash data that we are explicitly sending to these companies. All iNaturalist servers are provided and hosted by Microsoft, all iNaturalist images are hosted by Amazon, and almost all iNaturalist maps are served by Google, which means every time you look at an observation on iNaturalist, you are connecting to services provided by these companies and exposing your IP address to them, at the very least (in the iPhone app we use Apple’s maps). iNaturalist probably would not exist without the services these companies provide, and while we can limit the amount and kinds of data you share with them while using iNat, we cannot stop the flow of data entirely.
- [x] Ensure `prefers_no_tracking` gets returned in API responses when a client makes an authenticated request to get information about the authenticated user
- [ ] Ensure `prefers_no_tracking` can be updated via the API as well
