### ISSUE TITLE
Add Observations Component

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#957]
# Functional Spec

https://docs.google.com/document/d/16XbwM2hQe3E160YMUehQjmw_uBOAW0Q8X0bKFnh5ITg/edit?usp=sharing

# Prototype

http://thinkmoredesign.com/inat/Add_Obs/start.html

# Prototype Notation 

### Notes are indicated by this little icon...

![image](https://cloud.githubusercontent.com/assets/11527994/14335564/201d9a06-fc11-11e5-999b-194439053a12.png)

### Sitemap is featured on the left... 
![image](https://cloud.githubusercontent.com/assets/11527994/14335579/376c1dcc-fc11-11e5-9d8b-9dd90cd68f98.png)

* Only the pages with "(IX)" in the title are for demonstrated interactions. 
* Make sure to click on the "Page Notes" tab for overall page notes
* I was not able to make all interaction so please ask questions! Tried to make up for it in notation. 
* Please use all bootstrap css for now which means it does not all have to look exactly like the prototype or even close

## Making a New Ob from an Ob with Multiple Photos:

You can drag a photo out of it's mini slider and situate it in between any of the ob snippets to create a new one. 

# Questions

* Do we need some sort of sort filter? ...so you could sort obs by timestamp, species name, etc.
* Please take a look at the photo enlargement of an ob with multiple photos and tell me what you think. I added a mini carousel and drag drop capability to reorder photos. (The drag dropping doesn't actually work in the prototype.)

@pleary thanks for your patience! I am happy to walk you through the prototype again.

**Comment by joellebel** [comment]
# Drag Photo onto Other Ob
One other thing that's not in the prototype and I wasn't sure if we were going to have this for the first release is the ability to drag just a photo from one ob and drop it onto another ob to add only that photo to that ob. In this case you wouldn't get the Conflict pop up because the photo will take on the obs info. 

# Projects

Note that I also added projects just in case we want to to do them.

**Comment by loarie** [comment]
Three things to consider:
1. Adding an Alert on Submit when there are observations without coordinates

2. Adding an Alert on Submit when there are observations without IDs or photos (optionally additional or placeholder or description)

3. implementing the captive cultivated flag as in:
http://thinkmoredesign.com/inat/Add_Obs/start.html#p=single_ob_edit_and_location_flow__ix_
<img width="630" alt="screen shot 2016-04-13 at 4 09 57 pm" src="https://cloud.githubusercontent.com/assets/598026/14512265/5b46630c-0192-11e6-97d4-a87f39f355af.png">

My preference is yes to 1,2,3 with no preference for the optional or-placeholder-or-description constraints or not.

Thoughts @joellebel @alexshepard @kueda @pleary ?

**Comment by loarie** [comment]
4. Add placeholder/search external to the species chooser e.g.
<img width="476" alt="screen shot 2016-04-13 at 4 24 09 pm" src="https://cloud.githubusercontent.com/assets/598026/14512474/36071896-0194-11e6-9427-c52550230bcd.png">

**Comment by kueda** [comment]
I've tried to avoid visual design issues since I suspect Joelle will want to take a pass at that, so these are mostly just functional / interactive todos.

SPEC DISCREPANCIES

- [ ] There should be one "Add" button in the header and it should be a drop down as per http://thinkmoredesign.com/inat/Add_Obs/start.html#p=add_ob_no_photo_-_added__ix_, instead of a a "New/Blank" button and an "Add" button
- [ ] Adding a photo does not show a progress bar as spec'd at http://thinkmoredesign.com/inat/Add_Obs/start.html#p=loading_photos_obs. Is that even possible?
- [ ] Ability to drag a photo out of an existing observation to create a new one as spec'd at http://thinkmoredesign.com/inat/Add_Obs/start.html#p=make_new_ob_from_photo__ix_
- [ ] Button in header to combine selected obs as shown at http://thinkmoredesign.com/inat/Add_Obs/start.html#p=make_new_ob_from_photo__ix_ (though shown inconsistently in the spec, I think this is useful)
- [ ] Handle upload of non-image files, i.e. show an error message, don't add a new obs to the screen: http://thinkmoredesign.com/inat/Add_Obs/start.html#p=invalid_format
- [ ] Handle attempt to submit when there's no longer a working internet connection. I would prefer showing an alert and stopping submission, and would hope submission would be possible if/when I reconnected.
- [ ] Handle attempt to submit when request times out
- [ ] Add photo magnifier as specified at http://thinkmoredesign.com/inat/Add_Obs/start.html#p=combined
- [ ] Entire card should be draggable to combine, not just the target in the upper left corner, Rectangular selection should only starts when mousedown occurs outside of a card
- [ ] Submit button should read "Submit x Observations" and not have an icon
- [ ] Clicking on a blank location field should launch the location editing modal as per http://thinkmoredesign.com/inat/Add_Obs/start.html#p=single_ob_edit_and_location_flow__ix_

BUGS

- [ ] On dragging in a photo I get `Uncaught Invariant Violation: Expected targetIds to be an array.` It doesn't seem to keep the thing from working though
- [ ] Clicking in a taxon choose brings up the dropdown as expected, but clicking out of it does not dismiss the dropdown
- [ ] Date/time chooser won't let me set a date with no time

OTHER

- [ ] Should be able to select multiple cards with SHIFT-click
- [ ] Buttons in Remove / Cancel dialog need space between them
- [ ] Batch update of location should not remove any fields, just add / update
- [ ] Show warning when trying to submit an observation with no photo AND no ID. Should warn user that they have an obs with no photo and no ID, ask them if they want to proceed with upload. No photo AND ID is ok.
- [ ] Show warning when trying to submit an observation with a photo but without date or location


THINGS WE STILL NEED TO DISCUSS

* Should we be able to change the order of photos within a single observation by drag-and-drop?


THINGS WE'VE TALKED ABOUT BUT ARE NOT DOING FOR THIS ROUND 

* conflict resolution
* add to projects
* add observation fields
* flagging captive / cultivated

IMO some of these are pretty important so we'll probably do another round before release, but I think it will be good to test it on some people before another round of dev.

**Comment by pleary** [comment]
- Not sure we can do the upload progress bar. I put in a spinning loading indicator in it's place for now
- "Button in header to combine selected obs" - are we keeping the combine obs feature? We said in standup yesterday we might not want it this round. If we do need that fir the first release, then we'll also need the conflict resolution modal (which you say we're not doing. So I guess I need detailed spec on merging cards if we do that). The answer to that plays heavily into the drag to select since the selection and drag to merge share a lot of events which don't play nicely together. Personally, I'd rather ditch the ability to merge obs altogether only allow users to drag the images, not the whole card.
- "clicking out of [the taxon chooser] does not dismiss the dropdown". Another conflict with all the drag and drop/drag to select features. How hard this will be to do depends on all the other mouse actions, so I'll need confirmation about merging and what gets dragged
- "select multiple cards with SHIFT-click" it supports command+click. Is shift click a thing? Is there a library you know that does that?
- "Batch update of location should not remove any fields, just add / update" I don't follow. Could you provide an example?
- Various warnings are requested. What happens when we need to warn the user about several different things? Do they get one at a time? If so, what is the priority of warnings?

**Comment by pleary** [comment]
FYI for selection I'm using JQueryUI seletable https://jqueryui.com/selectable/, which clearly doesn't support shift + click to select. This might be pretty tricky to pull off. How important is it?

**Comment by loarie** [comment]
Apologies if I missed it - but also this more input options menu on SPEC DISCREPANCIES Correct
<img width="560" alt="screen shot 2016-04-14 at 12 31 53 pm" src="https://cloud.githubusercontent.com/assets/598026/14541058/e9165c1e-023c-11e6-83ce-5130c6d3b42d.png">

**Comment by pleary** [comment]
I thought we weren't doing any of that for now. If so, I'll need specs on just about all of those options

**Comment by loarie** [comment]
I think the 'not doing any of that for now' meant linking out to the existing http://www.inaturalist.org/observations/import
rather than rebuilding those flows

**Comment by pleary** [comment]
So what is the requirement. We need the dropdown and all of those options are links that make you leave the page and go somewhere else?

**Comment by loarie** [comment]
correct. Main advantage IMO being that we can eliminate any other links to that import view from the main menu without cutting off links to that functionality
<img width="116" alt="screen shot 2016-04-14 at 12 37 00 pm" src="https://cloud.githubusercontent.com/assets/598026/14541198/9f56d120-023d-11e6-9bf5-271237f8cdbe.png">
I don't feel strongly about this, but it was definitely discussed

**Comment by joellebel** [comment]
More specifically...

* "CSV" links to http://www.inaturalist.org/observations/import#csv_import
* "From Flickr" links to http://www.inaturalist.org/observations/import#photo_import
* "From SoundCloud" links to http://www.inaturalist.org/observations/import#sound_import

All these links open in the same window. 


The only thing I was unsure about was if we're keeping the ability to import from Google Picasa since it will soon become Google Photos and I don't know if that will require changes on our end.

**Comment by loarie** [comment]
Since http://www.inaturalist.org/observations/import#photo_import is the same endpoint for FB, Flickr, Picasa - how about sticking with 'Import from other photo sites' or is that confusing? 'From Flickr, etc.' or just 'From Flickr' since thats 90% of it?

**Comment by kueda** [comment]
> Not sure we can do the upload progress bar.

Got it. IMO the current treatment is too easy to miss, but not a deal breaker for me.

> "Button in header to combine selected obs" - are we keeping the combine obs feature?

Maybe I'm confusing language. Currently you can drag one card onto another and that merges the two observations, so I imagine a button in the header would do the same thing for selected observations, and just choose the first observation as the observation that remains, with no conflict resolution. I'm fine with the only-dragging-images solution you proposed too, but a button would still basically do the same thing in my mind.

> "select multiple cards with SHIFT-click" it supports command+click. Is there a library you know that does shift+click? We can definitely make it work, but if something else supports it natively that could be better.

I don't know of a library, this is just my expectation in any context where I can select multiple things. Usually CMD/CTRL-click adds the individual thing clicked the selection, and SHIFT-click selects everything in sequence from the current selection to the thing clicked. Supporting this is not a requirement in my mind, just something I immediately expected to work. If it's hard, don't bother for now.

> "Batch update of location should not remove any fields, just add / update" I don't follow. Could you provide an example?

The only use case might be for crazies like me: I often update the `place_guess` on multiple observations but I don't want to touch the coordinates. Maybe not a requirement, but I'm curious to see if this comes up in testing.

> Various warnings are requested. What happens when we need to warn the user about several different things? Do they get a big list, or one at a time? If it's one at a time, what is the priority of warnings?

Hm. So for the things that offer the user the chance to proceed or cancel (photo with no location, photoless obs with no ID), I think we need to show multiple warnings in one window. For no internet and timeout I think those will be mutually exclusive, right? For the warning when adding invalid files... I think the only problem would be if you added a bunch of files and only some of them are not valid types. In that case, I think a single warning like "Some of the files you added could not be imported."

Does that make sense? Maybe this needs discussion.

**Comment by joellebel** [comment]
# Screenshots

It appears not all icons are showing up in the prototype for some folks so I'm posting screenshots here. Thought I would only post the important ones since many of the screens have the same icons. Please let me know if you have any questions or need anything else! (Sadly, I can't fix this because my trial has expired)

Please note, some of the pages are missing the Combine button which should be located to the right of the remove button. The combine button is disabled unless two or more obs are selected. See below design...

![image](https://cloud.githubusercontent.com/assets/11527994/14615872/a767cc30-055c-11e6-81a3-d62165cd7029.png)


# Uploader Home
Note: The ob submit button in the upper right is not visible until obs have been added.

![image](https://cloud.githubusercontent.com/assets/11527994/14615643/7f7321b2-055b-11e6-9e08-92a8b77ac311.png)

# Add Ob No Photo - Added (IX)

![image](https://cloud.githubusercontent.com/assets/11527994/14615723/e6a80ae6-055b-11e6-9224-fe59ab87ba05.png)


# Loading Photos

We are going with the spinner now, but just thought I'd post a screenshot of this...

![image](https://cloud.githubusercontent.com/assets/11527994/14615737/f0168940-055b-11e6-91ea-c0210506428b.png)

# Single Ob Edit and Location Flow (IX)

![image](https://cloud.githubusercontent.com/assets/11527994/14615758/1475247c-055c-11e6-83d6-5584619fe01a.png)

# Location Advancd Edit (IX)

![image](https://cloud.githubusercontent.com/assets/11527994/14615790/41650dd0-055c-11e6-96ea-418c1016b26f.png)

# Edit/Combine 2 Obs (IX)

(Disregard the fact that the Upload button in the upper right is missing)
![image](https://cloud.githubusercontent.com/assets/11527994/14615988/337009fe-055d-11e6-8657-da2e6eda1b18.png)


# Card Hover State

![image](https://cloud.githubusercontent.com/assets/11527994/14616028/6cf7d670-055d-11e6-92ea-f81c6fdc5fce.png)

**Comment by kueda** [comment]
Functional review:

- [ ] This is still happening for me in Chrome: when dragging a photo onto the screen, the droppable area is only the upper half of the screen. Photos should be able to be dropped anywhere below the add obs nav. I think this is just one of those horrible height control issues. Might be solvable with flex box.
- [ ] Dragging a photo out of a card always adds it to the end, not to where you dragged it. Pretty confusing if you can't see the bottom of the screen, but not a deal-breaker
- [ ] Can we change import "From Flickr" to "From Flickr, Facebook, etc."?
- [ ] When you drag a card onto another card, the photo from the dragged card should not become the first photo. Currently it's doing that if the dragged card appears before the target card in sequence.

Questions:

1. Do we need a select none button? I don't, but maybe not everyone will know to click outside of the selection
1. Do we need to bring back that drag handle? I want to keep a fully draggable card, but we might need some draggable affordance for situations where it's hard to click the edges of the card.
1. Currently you can select multiple cards by just clicking them, not SHIFT- or CMD- clicking them. Not necessarily against this, but it might cause problems. My expectation is for a single normal click to select just the thing I clicked. Keep or change?

**Comment by loarie** [comment]
Only weird thing I've noticed is that changing the map marker circle size doesn't update the accuracy field (whereas changing the accuracy field does update the marker circle size)

**Comment by joellebel** [comment]
@kueda The "Select All" should be a checkbox so when you uncheck it, all should be unselected.

**Comment by joellebel** [comment]
# Design Specs

@pleary Here's some html you grab where easy or necessary (I have all the elements exposed (delete button, captive label, etc) so you can see what they look like: http://thinkmoredesign.com/inat/Dashboard/add_obs_06.html

![image](https://cloud.githubusercontent.com/assets/11527994/14860054/c14a361e-0c5b-11e6-9bc0-856b6cd2c6d1.png)


## Punch List

- [ ] Please remove the "Submit" button when there are no obs to upload
- [ ] Main Nav: Please see above page for how the add obs nav should look; The current method used for making disabled states is fine

### Cards
- [ ] please make the the rotating loading gif 1/3rd its size as well as the hour glass icon
- [ ] *Hover state for card:* 3px solid #74ac00 at 30%; Drag state:  3px solid #74ac00 at 100%; When dragging onto another card, the card being dragged onto should have a border of  5px solid #74ac00 at 100%
- [ ] *Photo Drag:* While photo is being dragged, please give it a border of 2px solid  #74ac00
- [ ] You can grab the Captive "C" label from above page
- [ ] Cards are 220px wide (they can be about that if the varying borders on hover and grab screw with things; The idea is that they're close to 220px)
- [ ] Cards input fields have the "input-sm"
- [ ] The cards on Staging are not using the bootstrap default border. Please see the CSS I used for the cards (I tried to use as little custom as possible). I'm just using the default .thumbnail border. As you can see I used this [component] (http://getbootstrap.com/components/#thumbnails-custom-content) as a model
- [ ] Cards have a margin-right of 15px
- [ ] See CSS for photo border and dropshadow
- [ ] I gave the input fields a top and bottom margin of 10px; The input fields are also within the ".caption" div which give the form fields a left and right padding of 9px on top of the 4px they afforded by the ".thumbnail" div
- [ ] Photo Width: I have the photo width and height not going beyond 164px (but it doesn't have to perfect; that's what worked for me with my css)
- [ ] See CSS used to create Remove round buttons. Please make them red on hover. The regular "red" is fine. 
- [ ] See CSS for regular and hover states for the magnifying glass; The hope was that the magnifying glass could always be in the lower left corner of the image
- [ ] Please put the slideshow chevrons on the outside of the photo so there is no overlapping while still maintaining their left and right alignments with the text fields; I have the chevrons for their regular state at #555; .5 opacity is fine for their disabled state. Hover state can be black. 


### Columns

- [ ] Please un-italicize the "Editing # observations / Select Observations to edit..." title in the left column
- [ ] Fields in the left column do not have the additional "input-sm" class as they are default-sized
- [ ] Please see what I did for columns. The left column has a fixed width of 290; The right column is fluid
- [ ] See below margins for the columns
 

![image](https://cloud.githubusercontent.com/assets/11527994/14861385/dfb15898-0c61-11e6-8cc5-fb5b64378662.png)



## Notes:

* I left out tagging styling. No worries on that. Think it looks ok. 
* Disregard the photo number count (ex. 1/2), if we're not doing them.

# Questions

* Are we leaving out the "Add Photo" button/link to a photo-less ob


Please let me know which of the above items are time consuming and/or what is not clear.

**Comment by joellebel** [comment]
This is looking great! Here's a couple nice-to-haves:

- [ ] When the enlarged photo slideshow is open it would be nice to close it by clicking anywhere outside of the photo (except when clicking the arrows, of course)

- [ ] Geoprivacy options are mixed capital and lowercase. It would nice if they were all capitalized

**Comment by pleary** [comment]
Thanks. I fixed the geoprivacy option capitalization, but I didn't do the slideshow thing yet. I originally had it the way you recommended, but I was often clicking out and was frustrated by it, and it might have messed with card selection. Not a big deal to change if people feel strongly about it.

**Comment by pleary** [comment]
The uploader is live, so I'm closing this ticket
